### ISSUE TITLE
Invalid flag: --release

### ISSUE THREAD

**Issue by duesee** [sensepost/mallet#10]
`mvn package`

yields

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project mallet: Fatal error compiling: invalid flag: --release -> [Help 1]
```

The solution is to remove the `<release>11</release>` tag in `pom.xml`. But this is certainly a hack to be able to build it. Is it?

This was discussed in https://github.com/sensepost/mallet/issues/4, but the issue was closed.

**Comment by zanzanYL** [comment]
Someone have a answer to this?

**Comment by RoganDawes** [comment]
I don’t honestly know the compatible way to support both earlier and later
versions of java.

If you are using a version earlier than 11, just remove that element from
the pom.
