### ISSUE TITLE
Could not initialize class com.sensepost.mallet.ognl.OgnlExpressions

### ISSUE THREAD

**Issue by christofersimbar** [sensepost/mallet#22]
Hi, I am getting the following errors when building:

Tests in error: 
  testHttpResponseMapping(com.sensepost.mallet.persistence.ObjectMapperTest)
  testHttpRequestMapping(com.sensepost.mallet.persistence.ObjectMapperTest): Could not initialize class com.sensepost.mallet.ognl.OgnlExpressions
  testWebsocketUpgradeResponseMapping(com.sensepost.mallet.persistence.ObjectMapperTest): Could not initialize class com.sensepost.mallet.ognl.OgnlExpressions
  testNoMapping(com.sensepost.mallet.persistence.ObjectMapperTest): Could not initialize class com.sensepost.mallet.ognl.OgnlExpressions

I am using Docker with the following image:
maven:3.6.3-jdk-8

What could be the cause of the problem? Does it require specific environment or other dependencies?

**Comment by RoganDawes** [comment]
I think I must have accidentally checked in a class that was not yet ready. Perhaps try deleting any OGNL-related classes if they give errors?

I'll have a look tomorrow and see if I can fix it up. My apologies!

**Comment by RoganDawes** [comment]
Fixed with https://github.com/sensepost/mallet/commit/7ebaf2ea9a423eeadef3fd876e14e6b047fd050c
