### ISSUE TITLE
BlazorPack messages onli visible in one direction

### ISSUE THREAD

**Issue by GStoynev** [sensepost/mallet#26]
Raising this as a complete newbie here... The example included in messagepack.mxe works, but it's only showing messages sent form the browser to the server. Is there a way to see server's responses, too?

**Comment by RoganDawes** [comment]
I'm surprised that you are only seeing messages in one direction. You *should* be seeing both READ and WRITE events, on both the browser to proxy (downstream) and proxy to server (upstream) channels. Even if you only added an interceptor on one channel (upstream or downstream), if you are seeing READ, you should also be seeing WRITE messages on that channel.

**Comment by RoganDawes** [comment]
To illustrate the above, the following image shows an HTTP request being READ on the Client to Proxy channel at +0.155s, the Proxy to Server channel is then established, and the same request is written to the Proxy to Server channel at +0.518S.

https://sensepost.com/img/pages/blog/2023/decoding-blazorpack/Screenshot-from-2022-02-04-15-18-22.png

The HTTP Response is then READ from the Proxy to Server channel at +1.485s, then written to the Client to Proxy channel also at +1.485s.

To conclude, if the app is functioning through the proxy, but you are only seeing READ events but not WRITE events for the return traffic, there is something seriously wrong, that I honestly can't imagine.

**Comment by GStoynev** [comment]
Thank you - it's either an oversight on my part/bad proxy configuration. I redid the setup and it's working as you describe it.

Great blog and example, btw.
