### ISSUE TITLE
Create Http2 and Http proxy

### ISSUE THREAD

**Issue by amit2103** [sensepost/mallet#9]
Hey , I want to create a proxy which supports Http2 and Http (Basically Http is fallback for Http).
Is it possible to do with mallet and how should I go about going with it ?

**Comment by RoganDawes** [comment]
Hi Amit,

Yes, this should be possible with Mallet, with the proviso that HTTP/2 is currently handled by translating HTTP/2 requests to HTTP/1 to cross the Relay node, then forwarded on to the final destination as HTTP/2 requests again.

I would suggest taking a look at the existing demo graph (demo.mxe) to see how regular HTTP and HTTPS can be handled (including WebSockets), then look at the HTTP2 demo (http2.mxe) to see how  the HTTP/2 graph is constructed. One thing to note is that there has been no testing of WebSockets over HTTP/2 yet.

**Comment by amit2103** [comment]
If i need to use it inside a Java application is there any source code for that ? Even guidance on how to use the handlers will be a great start

**Comment by RoganDawes** [comment]
The fun part of Mallet is that it essentially just a plain old Netty application, with a graphical pipeline builder on top of it. So, if you can build a Netty app, you should be good to go!

**Comment by amit2103** [comment]
No thats fine I meant to create such a proxy (with Http2 and Http) support
whats the handlers I should use

**Comment by RoganDawes** [comment]
The class names of the handlers are listed in the same graphs I referred you to in my first response.

**Comment by amit2103** [comment]
@RoganDawes  Thanks for the answer. I more or less setup the handlers.. Which part of the project is converting the Http2 to Http and back to Http.  Is it done in the Http2ToHttpServerInitializer and HttpToHttp2ClientInitializer ?

**Comment by RoganDawes** [comment]
Yes, exactly.

**Comment by amit2103** [comment]
@RoganDawes  If i need to start the Http2 graph from IDE how should I do it ?

**Comment by amit2103** [comment]
My bad figured it out  :)

**Comment by amit2103** [comment]
However when I try to set host:port as proxy in firefox , I cannot see the HTML pages in firefox is it by design or something is wrong ? This is using the demo graph

**Comment by RoganDawes** [comment]
Are you using an http or socks proxy in Firefox? The demo graph expects initial socks negotiation.

**Comment by amit2103** [comment]
Using that however it seems I cant open google.com , probably due to certification issues.

**Comment by RoganDawes** [comment]
Yes. Try a non SSL site first, just to verify things are working, then consider installing the Mallet CA cert into your browser to get past the browser cert validation.
The CA cert is generated new for each installation, so you don’t have to worry about it being abused.
